version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "${PRISMA_DB_PORT}:${PRISMA_DB_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_DB_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: ${PRISMA_DB_CONNECTOR}
            uri: >-
              ${PRISMA_DB_URI}